### ISSUE TITLE
Update WCAG term definition for "set of web pages"

### ISSUE THREAD

**Issue by maryjom** [w3c/wcag2ict#183]
WCAG 2.1 updated a "set of web pages" definition which we at least need incorporate and point to the alternate definitions for "set of software programs" and "set of documents". From WCAG 2.1:

>set of web pages
>collection of [web pages](https://www.w3.org/TR/WCAG22/#dfn-web-page-s) that share a common purpose and that are created by the same author, group or organization
>
>[EXAMPLE 28](https://www.w3.org/TR/WCAG22/#example-28)
>Examples include:
>
>- a publication which is split across multiple Web pages, where each page contains one chapter or other significant section of the work. The publication is logically a single contiguous unit, and contains navigation features that enable access to the full set of pages.
>- an e-commerce website shows products in a set of Web pages that all share the same navigation and identification. However, when progressing to the checkout process, the template changes; the navigation and other elements are removed, so the pages in that process are functionally and visually different. The checkout pages are not part of the set of product pages.
>- a blog on a sub-domain (e.g. blog.example.com) which has a different navigation and is authored by a distinct set of people from the pages on the primary domain (example.com).
>
>NOTE
>Different language versions would be considered different sets of Web pages.

### set of documents
>The term set of documents, as used in WCAG2ICT, has the meaning below:
>
>set of documents (non-web) (as used in WCAG2ICT)
>group of [documents](https://wcag2ict.netlify.app/#document) that are published together, and where the items all refer to each other by name or link
>
>NOTE
>Republishing or bundling previously published documents as a collection does not constitute a set of documents.
>
>NOTE
>If a set is broken apart, the individual parts are no longer part of a set, and would be evaluated as any other individual document is evaluated.
>
>Example: One example of a set of documents would be a three-part report where each part is a separate file. The table of contents is repeated at the beginning of each file to enable navigation to the other parts.
### set of software programs (as used in WCAG2ICT)
>group of [software](https://wcag2ict.netlify.app/#software) programs that are distributed together and that can be launched and used independently from each other, but that are interlinked each with every other one such that users can navigate from one program to another via a consistent method that appears in each member of the set
>
>NOTE
>This definition of “set of software programs” is derived from the characteristics of a “set” of web pages, and is used for mapping WCAG success criteria to software. Although such sets occur frequently for web pages, such sets appear to be extremely rare for software.
>
>NOTE
>Redistributing or bundling previously distributed software as a collection does not constitute a set of software programs.
>
>NOTE
>Consistent does not mean identical. For example, if a list of choices is provided it might not include the name of the current program.
>
>NOTE
>If a member of the set is separated from the set, it is no longer part of a set, and would be evaluated as any other individual software program.
>
>NOTE
>Any software program that is not part of a set, per this definition, would automatically satisfy any success criterion that is specified to apply to “sets of” software (as is true for any success criterion that is scoped to only apply to some other type of content).
>
>NOTE
>If there is any ambiguity whether the group is a set, then the group is not a set.
>
>NOTE
>If there is no independent method to launch the software programs (as is common in closed products), those programs would not meet the definition of a "set of software programs".
>
>NOTE
>Although the term “software” is used throughout this document because this would apply to stand alone software programs as well as individual software components and the software components in software-hardware combinations, the concept of “set of software programs” would only apply (by definition) to programs that can be launched separately from each other. Therefore, for the provisions that use the phrase “set of” (success criteria 2.4.1, 2.4.5, 3.2.3, and 3.2.4), the phrase “set of software programs” is used.
>
>**Example:** One example of a set of software programs would be a group of programs that can be launched and used separately but are distributed together and all have a menu that allows users to launch, or switch to, each of the other programs in the group.
>
>**Counterexamples:** Examples of things that are not sets of software programs:
>
>- A suite of programs for authoring different types of documents (text, spreadsheets, presentations, etc.) where the programs don't provide an explicit, consistent means to launch, or switch to, each of the other programs in the group.
>- An office package consisting of multiple programs that launches as a single program that provides multiple functionalities such as writing, spreadsheet, etc., but the only way to navigate between programs is to open a document in one of the programs.
>- A bundle of software programs that is sold together but the only way to navigate between the programs in the bundle is to use a platform software level menu to navigate between them (and not via a menu provided by each program that allows you to navigate to just the other programs in this bundle).
>- A group of programs that was a set, but the programs have been moved to separate locations so that their “set” behaviors were disrupted and no longer work. Even though they were a set at one time, because they are no longer installed as a set they no longer are a set and would not need to meet any success criteria that apply to sets of software.

**Comment by maryjom** [comment]
Proposal to incorporate "set of web pages" definition to the WCAG2ICT note:

Add "set of web pages" to the [Glossary Items with Specific Guidance](https://wcag2ict.netlify.app/#glossary-items-with-specific-guidance) section. Handle similarly to "content" where it simply points to the Key Terms section's definition of content. Here's how that would look:
>set of web pages
information and sensory experience to be communicated to the user by means of a user agent, including code or markup that defines the content's structure, presentation, and interactions
>
>### Guidance When Applying “set of web pages” to Non-Web Documents and Software
>See the guidance on [set of documents](https://wcag2ict.netlify.app/#set-of-documents) and [set of software programs](https://wcag2ict.netlify.app/#set-of-software-programs) in the Key Terms section.

------------------
Options for handling the definitions themselves in the Key Terms section:
1. Leave the definitions for "set of documents" and "set of software programs" as they were in the 2013 WCAG2ICT Note.
2. Make the definitions for "set of documents" and "set of software programs" match more closely to the new WCAG definition by starting with the WCAG definition and adding in the word substitutions for "web pages". This means there will need to be a note added that contains verbiage from the original WCAG2ICT definition. Proposal as follows:

### set of documents
>The term set of documents, as used in WCAG2ICT, has the meaning below:
>
>set of documents (non-web) (as used in WCAG2ICT)
>collection of [non-web documents](https://wcag2ict.netlify.app/#document) that share a common purpose and that are created by the same author, group or organization

>NOTE 
>A set of documents are published together where the items all refer to each other by name or link.
>
>NOTE
>Republishing or bundling previously published documents as a collection does not constitute a set of documents.
>
>NOTE
>If a set is broken apart, the individual parts are no longer part of a set, and would be evaluated as any other individual document is evaluated.
>
>Example: One example of a set of documents would be a three-part report where each part is a separate file. The table of contents is repeated at the beginning of each file to enable navigation to the other parts.
### set of software programs (as used in WCAG2ICT)
>collection of [software](https://wcag2ict.netlify.app/#software) that share a common purpose and that are created by the same author, group or organization
>NOTE
>Sets of software programs are distributed together and can be launched and used independently from each other, but are interlinked each with every other one such that users can navigate from one program to another via a consistent method that appears in each member of the set. Although such sets occur frequently for web pages, such sets appear to be extremely rare for software.
>
>NOTE
>Redistributing or bundling previously distributed software as a collection does not constitute a set of software programs.
>
>NOTE
>Consistent does not mean identical. For example, if a list of choices is provided it might not include the name of the current program.
>
>NOTE
>If a member of the set is separated from the set, it is no longer part of a set, and would be evaluated as any other individual software program.
>
>NOTE
>Any software program that is not part of a set, per this definition, would automatically satisfy any success criterion that is specified to apply to “sets of” software (as is true for any success criterion that is scoped to only apply to some other type of content).
>
>NOTE
>If there is any ambiguity whether the group is a set, then the group is not a set.
>
>NOTE
>If there is no independent method to launch the software programs (as is common in closed products), those programs would not meet the definition of a "set of software programs".
>
>NOTE
>Although the term “software” is used throughout this document because this would apply to stand alone software programs as well as individual software components and the software components in software-hardware combinations, the concept of “set of software programs” would only apply (by definition) to programs that can be launched separately from each other. Therefore, for the provisions that use the phrase “set of” (success criteria 2.4.1, 2.4.5, 3.2.3, and 3.2.4), the phrase “set of software programs” is used.
>
>**Example:** One example of a set of software programs would be a group of programs that can be launched and used separately but are distributed together and all have a menu that allows users to launch, or switch to, each of the other programs in the group.
>
>**Counterexamples:** Examples of things that are not sets of software programs:
>
>- A suite of programs for authoring different types of documents (text, spreadsheets, presentations, etc.) where the programs don't provide an explicit, consistent means to launch, or switch to, each of the other programs in the group.
>- An office package consisting of multiple programs that launches as a single program that provides multiple functionalities such as writing, spreadsheet, etc., but the only way to navigate between programs is to open a document in one of the programs.
>- A bundle of software programs that is sold together but the only way to navigate between the programs in the bundle is to use a platform software level menu to navigate between them (and not via a menu provided by each program that allows you to navigate to just the other programs in this bundle).
>- A group of programs that was a set, but the programs have been moved to separate locations so that their “set” behaviors were disrupted and no longer work. Even though they were a set at one time, because they are no longer installed as a set they no longer are a set and would not need to meet any success criteria that apply to sets of software.

**Comment by maryjom** [comment]
One question that remains is how to handle the WCAG note:
>NOTE
>Different language versions would be considered different sets of Web pages.

I don't think this same reasoning applies to non-web documents or software. Sometimes multiple languages are supported in a single software program. Sometimes to separate programs, but still they are not a "set" individually or together. Should we have notes for both non-web documents and non-web software that this particular WCAG note does not apply outside of the web?

**Comment by GreggVan** [comment]
This definition has a problem.  But it is easily fixed

Some of the notes in the PROPOSAL were key to the definition - but "by definition (sorry)"  notes are not part of a definition - 
Notes are informative and only meant to clarify what the words mean.

So we need to incorporate a couple of the notes in the definitions  

That would make it:    (and I think these are good ) 


The term set of documents  or set of software, as used in WCAG2ICT, have the meanings below:
set of documents (non-web) (as used in WCAG2ICT)

collection of non-web documents that share a common purpose and that are created by the same author, group or organization where the documents are published together and all refer to each other by name or link.

NOTE
Republishing or bundling previously published documents as a collection does not constitute a set of documents.

NOTE
If a set is broken apart, the individual parts are no longer part of a set, and would be evaluated as any other individual document is evaluated.
Example: One example of a set of documents would be a three-part report where each part is a separate file. The table of contents is repeated at the beginning of each file to enable navigation to the other parts.


set of software programs (as used in WCAG2ICT)
collection of software that share a common purpose, are created by the same author, group or organization and that are distributed together and can be launched and used independently from each other, but are interlinked each with every other one such that users can navigate from one program to another via a consistent method that appears in each member of the set. 

NOTE
Although such sets occur frequently for web pages, such sets appear to be extremely rare for software.

NOTE
Redistributing or bundling previously distributed software as a collection does not constitute a set of software programs.

NOTE
Consistent does not mean identical. For example, if a list of choices is provided it might not include the name of the current program.

NOTE
If a member of the set is separated from the set, it is no longer part of a set, and would be evaluated as any other individual software program.

NOTE
Any software program that is not part of a set, per this definition, would automatically satisfy any success criterion that is specified to apply to “sets of” software (as is true for any success criterion that is scoped to only apply to some other type of content).

NOTE
If there is any ambiguity whether the group is a set, then the group is not a set.

NOTE
If there is no independent method to launch the software programs (as is common in closed products), those programs would not meet the definition of a "set of software programs".

NOTE
Although the term “software” is used throughout this document because this would apply to stand alone software programs as well as individual software components and the software components in software-hardware combinations, the concept of “set of software programs” would only apply (by definition) to programs that can be launched separately from each other. Therefore, for the provisions that use the phrase “set of” (success criteria 2.4.1, 2.4.5, 3.2.3, and 3.2.4), the phrase “set of software programs” is used.

Example: Example of something that would be a set of software programs:
A group of programs that can be launched and used separately but are distributed together and all have a menu that allows users to launch, or switch to, each of the other programs in the group.

Counterexamples: Examples of things that are not sets of software programs:
A suite of programs for authoring different types of documents (text, spreadsheets, presentations, etc.) where the programs don't provide an explicit, consistent means to launch, or switch to, each of the other programs in the group.
 An office package consisting of multiple programs that launches as a single program that provides multiple functionalities such as writing, spreadsheet, etc., but the only way to navigate between programs is to open a document in one of the programs.
A bundle of software programs that is sold together but the only way to navigate between the programs in the bundle is to use a platform software level menu to navigate between them (and not via a menu provided by each program that allows you to navigate to just the other programs in this bundle).
A group of programs that was a set, but the programs have been moved to separate locations so that their “set” behaviors were disrupted and no longer work. Even though they were a set at one time, because they are no longer installed as a set they no longer are a set and would not need to meet any success criteria that apply to sets of software.


gregg

------------------------------
Gregg Vanderheiden
***@***.***

**Comment by maryjom** [comment]
@GreggVan If you have thoughts on how to handle or if we should add anything to explain or counter WCAG's note on language versions, I'd love to hear it. See the  [comment](https://github.com/w3c/wcag2ict/issues/183#issuecomment-1622099236) where I posed the question and some alternatives for handling.

**Comment by maryjom** [comment]
The TF reached [consensus on the definition of "set of web pages"](https://www.w3.org/2023/07/13-wcag2ict-minutes.html#r04) on 13 July. The AG WG [reviewed "set of web pages"](https://www.w3.org/2002/09/wbs/55145/WCAG2ICT-Third-content-review-by-AGWG2/results#xq13) in the 3rd content review and reached consensus on 25 July.
