### ISSUE TITLE
WCAG2ICT FPWD comments: email from Craig Keefner regarding kiosks

### ISSUE THREAD

**Issue by pday1** [w3c/wcag2ict#215]
**WCAG2ICT process for comments:** 
[Process-for-addressing-public-comments](https://github.com/w3c/wcag2ict/wiki/Process-for-addressing-public-comments)

**Original comment:** 
[Comment from Craig Keefner](https://lists.w3.org/Archives/Public/public-wcag2ict-comments/2023Aug/0000.html)

**Proposed edits for draft response:**
Thanks for taking the time to comment on this draft. The task force has spent a lot of time considering closed functionality products, including kiosks. We also have some participants within the task force with experience working with kiosks (both software and hardware). Sending out drafts for public review is an important way for our task force to obtain a wider review of the WCAG2ICT document. We welcome your input and that of others in your association who may have more diverse product knowledge, as we recognize that this is a challenging area. If there are specific changes that you think are required, please submit your comments. You may find the sections focusing on Closed Functionality to be particularly relevant to kiosks (including [Section 3](https://urldefense.com/v3/__https://www.w3.org/TR/wcag2ict/*closed-functionality__;Iw!!In4Qlw!p9mSjlQeOV1pFsCYuLtrAr6PswWSFs29M3hx2jjzPlX3u22xFfkfHESmNKohM926saA8m4ihWlc-5A$), and [Appendix A](https://urldefense.com/v3/__https://www.w3.org/TR/wcag2ict/*success-criteria-problematic-for-closed-functionality__;Iw!!In4Qlw!p9mSjlQeOV1pFsCYuLtrAr6PswWSFs29M3hx2jjzPlX3u22xFfkfHESmNKohM926saA8m4jvkRKWug$)).
 
We are still working on updates to [Appendix A](https://urldefense.com/v3/__https://www.w3.org/TR/wcag2ict/*success-criteria-problematic-for-closed-functionality__;Iw!!In4Qlw!p9mSjlQeOV1pFsCYuLtrAr6PswWSFs29M3hx2jjzPlX3u22xFfkfHESmNKohM926saA8m4jvkRKWug$), so any input you submit can help us to refine and further improve this section.

**Comment by Lboniello** [comment]
I would like to see a note about the scope of WCAG2ICT for any comments submitted. We struggled with limiting scope, so it would be natural for those that were not involved to attribute greater scope to this committee than constraints dictate.  I'd like to add something along the lines of . . . 

"WCAG2ICT recommendations are limited in scope to applying WCAG to ICT. Hardware requirements are largely outside of the scope of this committee, as are specific hardware/software interactions."

**Comment by bruce-usab** [comment]
Thanks @pday1 for starting this issue for our first comment via email!

@Lboniello (et al.) do we want to go even further?

> WCAG2ICT recommendations are limited in scope to applying WCAG to non-web documents and non-web software.  Hardware requirements are outside of the scope of this taskforce, as are specific hardware/software interactions.

@maryjom should the general topic of applicability of WCAG2ICT for hardware be a GitHub Discussion rather than an Issue?

From the [2013 WCAG2ICT](https://www.w3.org/TR/2013/NOTE-wcag2ict-20130905/) Abstract, right at the top:

>  This document ... describes how the Web Content Accessibility Guidelines (WCAG) 2.0 and its principles, guidelines, and success criteria can be applied to non-web Information and Communications Technologies (ICT), specifically to non-web documents and software.

It seems to me that this has gotten overlooked, even in some regulation.

**Comment by maryjom** [comment]
@bruce-usab This same text appears in the abstract, in the first sentence, at the top of our published draft. 
>This document, “Guidance on Applying WCAG 2.2 to Non-Web Information and Communications Technologies (WCAG2ICT)” describes how the Web Content Accessibility Guidelines (WCAG) 2.2 [[WCAG22](https://www.w3.org/TR/wcag2ict/#bib-wcag22)] and its principles, guidelines, and success criteria can be applied to non-web Information and Communications Technologies (ICT), specifically to non-web documents and software.

Also, there is the same Section 1.3 Out of Scope bullet that existed in the 2013 WCAG2ICT that says:
>This document does not comment on hardware aspects of products, because the basic constructs on which WCAG 2.2 is built do not apply to these.

So I'm unsure as to whether there's any confusion on that aspect.

**Comment by maryjom** [comment]
@Lboniello I'm not sure we need to expand the comment regarding not covering hardware, as the comment wasn't inquiring about that, and as Bruce points out we have that information up front in multiple places.  I'd like the response to be focused on the fact that we do have representation thinking about kiosks and we welcome any of his or other kiosk vendor comments on aspects of guidance for applying WCAG to kiosk software we have in our document that they have issues with.  It may be useful to point out that the TF is not at liberty to modify the normative WCAG language except where web-specific language is used in the Success Criteria. We write notes to cover any other caveats or thoughts about applying the criteria to non-web software and documents.

**Comment by bruce-usab** [comment]
> So I'm unsure as to whether there's any confusion on that aspect.

There is no confusion on that part for _us_, and I don't have any suggestions as to how WCAG2ICT might be clearer or stronger.

As to whether there's any confusion on that aspect,?  The answer is undoubtedly _**yes**_!

If there is no objection, I would like to start a GitHub Discussion thread with some examples.

**Comment by pday1** [comment]
RESOLUTION from task force meeting of 2023/08/24 is to approve the language above, reproduced here for clarity. 

**Approved response:**
Thanks for taking the time to comment on this draft. The task force has spent a lot of time considering closed functionality products, including kiosks. We also have some participants within the task force with experience working with kiosks (both software and hardware). Sending out drafts for public review is an important way for our task force to obtain a wider review of the WCAG2ICT document. We welcome your input and that of others in your association who may have more diverse product knowledge, as we recognize that this is a challenging area. If there are specific changes that you think are required, please submit your comments. You may find the sections focusing on Closed Functionality to be particularly relevant to kiosks (including [Section 3](https://urldefense.com/v3/__https://www.w3.org/TR/wcag2ict/*closed-functionality__;Iw!!In4Qlw!p9mSjlQeOV1pFsCYuLtrAr6PswWSFs29M3hx2jjzPlX3u22xFfkfHESmNKohM926saA8m4ihWlc-5A$), and [Appendix A](https://urldefense.com/v3/__https://www.w3.org/TR/wcag2ict/*success-criteria-problematic-for-closed-functionality__;Iw!!In4Qlw!p9mSjlQeOV1pFsCYuLtrAr6PswWSFs29M3hx2jjzPlX3u22xFfkfHESmNKohM926saA8m4jvkRKWug$)).

We are still working on updates to [Appendix A](https://urldefense.com/v3/__https://www.w3.org/TR/wcag2ict/*success-criteria-problematic-for-closed-functionality__;Iw!!In4Qlw!p9mSjlQeOV1pFsCYuLtrAr6PswWSFs29M3hx2jjzPlX3u22xFfkfHESmNKohM926saA8m4jvkRKWug$), so any input you submit can help us to refine and further improve this section.

**Comment by pday1** [comment]
Response has been sent via [email](https://lists.w3.org/Archives/Public/public-wcag2ict-comments/2023Aug/0001.html)

**Comment by maryjom** [comment]
**Follow-up comments:**

1. [Re: Comments on WCAG2ICT Overview](https://lists.w3.org/Archives/Public/public-wcag2ict-comments/2023Aug/0002.html) Craig Allen Keefner (Thursday, 24 August)
2. [Re: Comments on WCAG2ICT Overview](https://lists.w3.org/Archives/Public/public-wcag2ict-comments/2023Aug/0003.html) Craig Allen Keefner (Thursday, 24 August)

Proposed draft response:
Hi Craig,
To answer your questions:
- [ ] In the end, this document is just suggestions/recommended considerations regarding "closed systems" right?
    **Answer:** Yes. This document is not intended to set requirements (is non-normative). It is simply to provide interpretation of WCAG Success Criteria when applied to non-web software and documentation. The task force makes notes where this may not be easily adaptable, as in the Success Criteria Problematic for Closed Functionality section. It also provides guidance and word substitutions when web-specific language is used in WCAG success criteria which eases the interpretation. The intent is to help manufacturers as well as standards makers understand how widespread application of WCAG in non-web contexts can be done, yet to point out areas where such application may not be as easy – especially for closed functionality products where a user’s assistive technology cannot be installed.
- [ ] This doc is oriented to WCAG 2.2 right?
**Answer:** Yes. The first draft only has WCAG 2.1 since 2.2 is not yet a Recommendation. The next draft will include WCAG 2.2.
- [ ] What are the other closed systems besides your typical kiosk (McDonalds self-order e.g.)
**Answer:** The task force has been thinking about closed functionality beyond the specific “systems” examples mentioned in the document, knowing that technology has significantly changed since 2013.  It is debatable whether having a specific list is the document useful since it will become stale again over time. The task force has been thinking about a wide variety of closed functionality technology that has software. Examples include: printers, watches, iOT devices, telephones (including mobile and IP phones), smart speakers and televisions, set-top boxes (e.g. cable box, DVR), tablets, VR headsets, ATMs, PoS, and kiosks used for a variety of purposes (including travel kiosks used for ticketing and check-in). 
- [ ] What's the deadline for providing comments and where do I send them? 
**Answer:** The deadline for providing comments on this First Public draft is September 26. Comments can be made at any time before the WCAG2ICT update is a finalized Note by either sending comments to this mailing list or [opening a GitHub issue](https://github.com/w3c/wcag2ict/issues/new) in the WCAG2ICT document repository.
In response to your follow-up email, the task force appreciates that you took the time to post about the draft review to bring it to the attention of your colleagues in the KMA. Early public drafts provide the interim exposure to wider public review as the task force continues to develop content - a valuable part of the process. 
Since this draft focused on including new WCAG 2.1 requirements and definitions to the 2013 WCAG2ICT, it’s not surprising you found old technology examples of closed systems. We are still making further changes that include: updates for Closed Functionality software, adding WCAG 2.2 requirements and definitions, addressing open issues, and refreshing stale content in other sections. We have noted the outdated examples that require updates in [GitHub issue #217](https://github.com/w3c/wcag2ict/issues/217).

**Comment by Lboniello** [comment]
This reply is fantastic, @maryjom .  Since Craig's reply included mention of my name, and reference to the CSA B651.2 update released in 2022 (of which I was also a part), I do think that clarification would be helpful.   Your call as to whether any of this adds to your response, but I think it is important to note within the group at minimum. 

Whilst irrelevant to WCAG2ICT, Craig rmentions the "Canadians ADA rewrite" to which I presume he references the update to CSA B651.2. This standard combined the (Bank Machine) ABM standard with the self service standard.  As such, his comment that it was largely Diebold driven is incorrect (more it was meant to be inclusive of ABMs).   

We may not want to address that in our official response, but I want to clarify here that his statement to that point is entirely incorrect. Much like @pday1 has extensive ATM/ABM experience, John (of Diebold) provided crucial input to leverage expertise from ABM/ATM in the development of broader kiosk accessibility standards.  In addition, my job history includes years at a leading kiosk system software company, and establishes my expertise from within the kiosk software/kiosk industry. @samogami formerly of HP also provides vital perspective from closed systems within the peripheral device (printers etc.,) category and I am sure there are others that come from kiosk spaces directly or indirectly. 

Just wanted to make that point for our own knowledge, and in defense of the CSA working group on the topic as well.

**Comment by maryjom** [comment]
Thanks for that clarification, Laura. I do realize that many of us have been working in tech for quite some time and likely have much broader experiences and exposure to a wide variety of technologies over the course of our careers, which may also be beyond our current position and focus. It might be best to abstain from the back-and-forth on this. If you wish to respond directly, that is your prerogative. I personally have an electrical engineering background, have worked on communications systems software, assistive technology and eventually landed in accessibility standards and policy.

In my proposal I simply further encourage review and feedback by the widest group of stakeholders so we can provide every opportunity for input to help us refine the guidance.

Best regards,

Mary Jo Mueller
IBM Accessibility Standards Program Manager


From: Laura Boniello Miller ***@***.***>
Date: Monday, August 28, 2023 at 8:35 AM
To: w3c/wcag2ict ***@***.***>
Cc: Mary Jo Mueller ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [w3c/wcag2ict] WCAG2ICT FPWD comments: email from Craig Keefner regarding kiosks (Issue #215)
This reply is fantastic, @maryjom . Since Craig's reply included mention of my name, and reference to the CSA B651. 2 update released in 2022 (of which I was also a part), I do think that clarification would be helpful. Your call as to whether
ZjQcmQRYFpfptBannerStart
This Message Is From an External Sender
This message came from outside your organization.
    Report Suspicious  <https://us-phishalarm-ewt.proofpoint.com/EWT/v1/PjiDSg!2g-pItQcolPwkMXw8unGZfXnzPxzAzJ5Qfqpc4Na0eI53lh0hyH2EaEEd446L6hqaU3_ihgmMmRXuLBl8XDKBIM5HvOKd1k$>   ‌
ZjQcmQRYFpfptBannerEnd

This reply is fantastic, @maryjom<https://github.com/maryjom> . Since Craig's reply included mention of my name, and reference to the CSA B651.2 update released in 2022 (of which I was also a part), I do think that clarification would be helpful. Your call as to whether any of this adds to your response, but I think it is important to note within the group at minimum.

Whilst irrelevant to WCAG2ICT, Craig mentions the "Canadians ADA rewrite" to which I presume he references the update to CSA B651.2. This standard combined the (Bank Machine) ABM standard with the self service standard. As such, his comment that it was largely Diebold driven is incorrect (more it was meant to be inclusive of ABMs).

We may not want to address that in our official response, but I want to clarify here that his statement to that point is entirely incorrect. Much like @pday1<https://github.com/pday1> has extensive ATM/ABM experience, John (of Diebold) provided crucial input to leverage expertise from ABM/ATM in the development of broader kiosk accessibility standards. In addition, my job history includes years at a leading kiosk system software company, and establishes my expertise from within the kiosk software/kiosk industry. @samogami<https://github.com/samogami> formerly of HP also provides vital perspective from closed systems within the peripheral device (printers etc.,) category and I am sure there are others that come from kiosk spaces directly or indirectly.

Just wanted to make that point for our own knowledge, and in defense of the CSA working group on the topic as well.

**Comment by maryjom** [comment]
Based on the 31 August meeting feedback, I propose adding the following to the response in the very first bullet about WCAG2ICT providing non-normative interpretation of WCAG to non-web software and documentation:
>I also wanted to call to your attention that WCAG2ICT does not comment on hardware aspects of products, because the basic constructs on which WCAG 2.2 is built do not apply to these. This limitation of scope is listed in the [Excluded from Scope](https://w3c.github.io/wcag2ict/#excluded-from-scope) section.

**Comment by maryjom** [comment]
Email sent to the list on 7 September.

**Comment by maryjom** [comment]
This issue can be closed. The content changes from Craig's comment regarding examples will be tracked in Issue #217.

**Comment by ChrisLoiselle** [comment]
Unassigned myself as this is closed.
