### ISSUE TITLE
Success Criterion 11.1.4.10 Reflow (AA) applied to self-service terminals / kiosks

### ISSUE THREAD

**Issue by detlevhfischer** [w3c/wcag2ict#221]
I am scratching my head as I wonder how to apply WCAG2ICT 6.1.5.7 Reflow, corresponding to EN 301 549 (11).1.4.10 Reflow, to content on a self-service terminal.

In the system under test, there are no options to zoom in, text content is arranged as a series of slides (much like a Powerpoint presentation), with fairly large text.

In the WCAG2ICT draft, as in EN 301 549 V.3.2.1, the requirement 11.1.4.10 Reflow has no exceptions (apart from content that requires two-dimensional layout for usage or meaning, which is clearly not the case here), so it would seem to apply "as is" to self-service terminals.

- If the terminal offers no zoom-in option, does that mean that 11.1.4.10 is not applicable?
- Or does it mean the system needs to be modified to allow zoom and reflow to the equivalent of 320 CSS pixels (I disregard here the question of how that is best measured)? This would then have the consequence of also requiring scrolling (I think an alternative chunking of content to fit the same screen dimensions enlarged is not really an option).

For cases where zoom is not offered by a self-service terminal, it appears to me to be reasonable to measure the default text size and see if it meets 5.1.4 (Functionality closed to text enlargement) - (in 5.1.4, there is a device-independent method of measuring whether capital "H" subtends an angle of at least 0,7 degrees). If text is indeed large by default, it would appear to meet the spirit of 1.4.10 (give users large text without the need for sideways scrolling).

I was tempted to reopen the huge issue #98 but I guess it is easier to start a new one...

**Comment by mraccess77** [comment]
To me - SC 1.4.10 doesn't require text get larger nor that zoom be available.   It requires content fit in 320CSS pixel width for horizontal languages without requiring two-dimensional scrolling to read text.  So that is the test.

**Comment by patrickhlauke** [comment]
and if the display uses any dimensions other than 320 CSS pixels for vertical content / 256 CSS pixels for horizontal content (or platform equivalents for whatever a single CSS pixel base unit is), and there's no way for a user to set it to an equivalent either, then ... the SC does not apply? (leaving aside my usual grumblings about how ill-conceived the original wording of the SC is)

**Comment by maryjom** [comment]
Detlev, thank you for taking the time to review the WCAG2ICT public draft. Our task force will review your comment and develop a response that we hope will address your concern. The response will be drafted in a comment on this issue, marked **DRAFT RESPONSE** until the Task Force reaches consensus.

**Comment by mitchellevan** [comment]
Overlaps with #227 (emphasis mine):

> Do you have any guidance on how to measure the CSS pixel equivalents for macOS software, Window software, or **systems with closed functionality** for testing purposes?

**Comment by maryjom** [comment]
WCAG2ICT Task Force answer:

The WCAG2ICT Task Force received substantial feedback on 1.4.10 Reflow as there are concerns with applying it, as written, to all to non-web documents and software, including software on ICT with closed functionality. We have updated both the general guidance (See [Applying SC 1.4.10 Reflow to Non-Web Documents and Software](https://w3c.github.io/wcag2ict/#applying-sc-1-4-10-reflow-to-non-web-documents-and-software)) and the information in the [Success Criteria Problematic for Closed Functionality](https://w3c.github.io/wcag2ict/#success-criteria-problematic-for-closed-functionality) in the current editor’s to address the concerns. 

Self-service terminals and kiosks fall into the ICT with closed functionality where success criterion 1.4.10 Reflow now has the following guidance:
>- 1.4.10 Reflow— Some software on ICT with closed functionality does not support scrolling content, or zooming, or changing the viewport (examples include, but are not limited to, software for self-service transaction machines or kiosks). Therefore, some other non-WCAG requirements would be needed for products with closed functionality to ensure that content is readable by persons with low vision without scrolling in two dimensions.
>
>     NOTE 3: Some ICT with closed functionality does not display large chunks of text and only has UI controls. In such cases, two-dimensional scrolling to access the text and UI controls may be considered essential, thus meeting an exception, and the success criterion would be satisfied.

Since WCAG2ICT is not normative, it is up to standards that apply WCAG to non-web ICT to provide clarity in the requirement or provide alternate requirements to cover instances such as single screen design kiosks that do not have any scrollable content or technology that has no ability to resize the viewport and/or text size (which are typically required to support a minimum text size for content in the UI instead).

**Comment by maryjom** [comment]
We are closing this issue as answered.

**Comment by detlevhfischer** [comment]
> Therefore, some other non-WCAG requirements would be needed for products with closed functionality to ensure that content is readable by persons with low vision without scrolling in two dimensions

This sounds a bit as if there was nothing at all in standards like the EN 301 549 that reference WCAG in clause 9, 10 and 11 - but the EN has C.5.1.4 "Functionality closed to text enlargement", which mandates a minimum font size based on viewing angle.

**Comment by maryjom** [comment]
Though there are some requirements that exist to support persons with low vision, the minimum font size requirement does not specifically address what is required by 1.4.10 Reflow - scrollable in only one direction at the specified pixel width or height, depending on the whether scrolling is vertical or horizontal whenever there is scrollable content. It would be up to other standards organizations to see if any other requirement would be needed to cover this situation. WCAG isn't clear on what to do if the ICT doesn't support the viewport width (for vertical scrolling) or height (for horizontal scrolling) as specified, and standards would need to clear that up.

**Comment by mraccess77** [comment]
Viewport could also be taken to mean the window when I think this really could apply to any resizable control or area of a window.

**Comment by maryjom** [comment]
@mraccess77 Two questions. Are you suggesting a change in the language?  Is this something that would block publication?

**Comment by mraccess77** [comment]
@maryjom I'm not saying it should block publication.  I would be in favor or wording that allowed for any mechanism which might allow for adjusting the scrolling content at the specified width/height (which may include resizing the viewport or content).

**Comment by maryjom** [comment]
@mraccess77 I've opened Issue #394 to log and track this specific point.

I think the note is fine as-is for the specific issue reported by @detlevhfischer. The TF had considered adding in reference to outside standards having a requirement for a minimum text size, but since it really doesn't address the WCAG normative language for reflow, we chose to drop that from this SC.  There are multiple places where we mention there are other standards that have requirements for closed functionality, but since this is a non-normative document, we don't provide any lists of what those standards are.
