### ISSUE TITLE
More affirmative examples

### ISSUE THREAD

**Issue by melaniephilipp** [w3c/wcag2ict#225]
There are a few Success Criteria that would greatly benefit from going further than rewording the text by providing examples of non-web technologies that support the Success Criterion. Affirmative examples of how non-web technologies support an SC would be especially useful for:

- 1.3.5 Input Purpose (For example, there’s an equivalent for Android and iOS native mobile. Are there similar examples for desktop software?)
- 1.4.12 Text Spacing
- 1.4.10 Reflow

Conversely, if there are no known affirmative examples for non-web technologies, it would be extremely helpful to state so - similar to how WCAG2ICT states that “sets of software” appear to be extremely rare. That way people who are trying to apply the guidance know that theoretically this could apply, but no known examples actually exist in 2023. This will help keep people from spending a lot of time trying to apply the theoretical guidance where it isn't practically possible. 

Regarding “sets of software”, while WCAG2ICT states that “sets of software” appear to be extremely rare - do you know of any actual examples?

**Comment by maryjom** [comment]
Thank you for taking the time to review the WCAG2ICT public draft. Our task force will review your comment and develop a response that we hope will address your concern. The response will be drafted in a comment on this issue, marked **DRAFT RESPONSE** until the Task Force reaches consensus.

**Comment by bruce-usab** [comment]
@melaniephilipp on the TF call today, regarding only the "sets of software" term, no-one could think of contemporary examples.  During the time when the first WCAG2ICT was written, the TF did identify a couple products.  Regardless "sets of software" isn't something that can be ruled out as never being relevant.

**Comment by mraccess77** [comment]
Seems like Microsoft Office could be a set of software.

**Comment by bruce-usab** [comment]
@melaniephilipp would you access MS Word (desktop) as non-web example of 1.4.12?  Control over line and paragraph spacing is  easy.  There is also control for kerning which I think would hit the letter spacing metric.  However, I do not know how to adjust intra-word spacing.

For 1.4.10 Reflow, Adobe Reader (desktop app) has had the feature for years.

**Comment by melaniephilipp** [comment]
Thanks @bruce-usab I think for Documents, Text Spacing and Reflow are easier to apply. I probably should have scoped the question to examples of how the SCs are successfully met in Software like mobile apps and desktop apps. I realize this crosses over into testing, which isn't in your scope, but how does one know if a piece of software has the potential to meet the SC (or if it should be considered Not Applicable) if one doesn't understand how it COULD practically apply? For example, can Text Spacing be applied to any software? That's where practical examples would be helpful to everyone reading and applying WCAG2ICT. 

Thank you!

**Comment by mraccess77** [comment]
@bruce-usab I believe immersive reader functions in MS Word can adjust spacing between words as well as letters.

**Comment by mraccess77** [comment]
@bruce-usab In my experience you can edit a chart in PowerPoint that opens an Excel Window.  Also, in PowerPoint you can present into Teams.  You can/could embed different objects such as Excel into Word.  The office365 app is a launcher for the MS Office application- so they have a unified launcher as well.  So, to me they do feel like a set of software.

**Comment by bruce-usab** [comment]
@mraccess77 thanks for highlighting those features you!  I now agree that it would be fine and good to start using  MS Office as an example of "set of software".

@melaniephilipp examples of _mobile_ apps will be harder to come up.  But maybe we can find a reference in the developer guidance for iOS or Android?

**Comment by patrickhlauke** [comment]
assuming that the discussion around "set of software" is an attempt to translate "sets of web pages" ... wouldn't a more apt adaptation be "sets of related views/screens" within the same piece of software?

**Comment by maryjom** [comment]
@patrickhlauke The original WCAG2ICT Task Force went round and round on these specific SCs for literally months. Defining "views/screens" was part of the problem, defining granularity in which of them would be "related" within the software, etc. was also quite problematic. Since the TF is not at liberty to develop requirements, we felt it was best to not take the interpretation into that direction. Should other standards that define non-web software requirements decide to take that up, we felt that approach was a more appropriate way to do it. That's why we used "best practice" language in some of the notes for the "sets of web pages" SCs.

**Comment by patrickhlauke** [comment]
I'm just trying to work out if the TF indeed translated "sets of web pages" to mean "sets of software" for WCAG2ICT here, and if so suggest that this may not necessarily make much sense. Happy to discuss this in a separate issue, if that'd be more helpful, so as not to sidetrack the purpose of this issue here

**Comment by GreggVan** [comment]
Yes we did.   Only because we could not find an objective - non-slippery or foggy definition of "views" which would be more equivalent to pages.   But web apps have the same problem. 

So it is "sets of software"  and we note that it is rare to find any that meet out definition. 

For the original WCAG2ICT we found 3 and had a demo session with one.   But we had to search hard to find them.  

So those provisions don’t apply to something very often — actually very rarely.   The European EN 301 549 - which references the guidelines one by one and list software separately from web content — skipped those for software.

Gregg

**Comment by patrickhlauke** [comment]
"set of web pages" though refers to subcomponents of a website as a whole that is the subject of an assessment, while "software" *is* the whole that is being assessed. this seems to make little sense, regardless of the mitigation of "it doesn't happen often".

**Comment by GreggVan** [comment]
As I mentioned.   

The goal was to find an equivalent in software — but we could never find one.

If you have a suggestion please toss it in for discussion.

We only fell back to software as a whole because we could find nothing else that was better. 
It does indeed make sense when there are sets of software.    But it is rare and we thought it better to be views or "page-equivalents" within a piece of software.  But software is so dynamic and changes with each toolbar etc that is exposed that there are no -defined views - for most programs.

Note that web-apps have the same problem — and WCAG is applied by URL (the definition of a page) so web-apps create exactly the same problem….  

Again — if you have an idea - I think I can speak for the group and say  we would be happy to hear it.

Best

G

**Comment by patrickhlauke** [comment]
> But software is so dynamic and changes with each toolbar etc that is exposed that there are no -defined views - for most programs.

Then I would rather suggest that WCAG2ICT would outright state that because "set of web pages" is rooted on the concept of "web page", and that in turn is rooted on - per the definition - a resource available at a particular URL, the whole idea is not applicable to software at all since it has no concept of a URL. Rather than making an ill-fitting stretch to mean "set of software".

Or refer to "set of software applications within a suite of applications", assuming that the subject of an assessment is indeed the suite as a whole...

> Note that web-apps have the same problem — and WCAG is applied by URL (the definition of a page) so web-apps create exactly the same problem

Just as an aside, many modern web apps actually dynamically change the URL in the browser exactly to make their sub-sections/views directly accessible (even though behind the scenes they may all be generated by a single monolithic script/page).

And yes, the WCAG definition (which dates back to 1999 or thereabouts) has outlived its usefulness in the last 23+ years...hoping that whatever shape WCAG 3 takes, it won't make this same sort of mistake. The intent of the SC is clearly about things that a user would perceive as being different pages, regardless of the technicality of "same URL" or not. But yes, for the ICT transposition of what the term should be interpreted as, I will start a separate thread with potentially better suggestions.

**Comment by maryjom** [comment]
@patrickhlauke Per your last comment. WCAG2ICT didn't say something didn't apply because the Task Force was clearly instructed that we couldn't do so. Thus the fact that we worked for months on a potential solution to essentially scope out what was not easily applicable to software, as written. We are having the same problem with "In content written in markup languages".  However, where a similar requirement could very well make sense in a non-web software or document context other standards organizations could develop additional requirements similar to these SC. Then they can modify the verbiage to be something that is more understandable and easily applicable.

**Comment by maryjom** [comment]
DRAFT TF ANSWER:

The Task Force discussed the potential to add examples. On the surface, this sounds like a good idea, but finding concrete examples of “sets of software” proves difficult.  However, we have decided that not to add affirmative examples to the document for the following reasons:
-       The guidance wouldn't be company/technology agnostic if we try to capture specific examples.
-       Technology changes over the years, so examples are only relevant for the specific moment in time when we are writing the guidance. Specific examples would become stale over time. 
 
Like some of your other good suggestions, this could be something developed outside of the work of this task force. As a W3C Note, development of WCAG2ICT is constrained by a tedious and time consuming process to update. Examples such as this might be better documented in a Wiki or other easily updated resource.

**Comment by pday1** [comment]
Additions from task force of 8th Feb 2024. 

Change tedious to comprehensive or long. 

Make the following additions:
The Task Force is declining to add more examples to the following, for these reasons:
1.3.5 Input Purpose: iOS or Android is a likely example where it will be relevant, but this Task Force is not in a position to decide whether there is currently sufficient accessibility support.
1.4.12 Text Spacing: Examples are sufficiently addressed in Note 1: "Examples of markup languages that are used internally...."
1.4.10 Reflow: This criterion links to the definition of "CSS pixel," which includes examples of platforms that use a density-independent pixel.

**Comment by maryjom** [comment]
FINAL TF ANSWER:

The Task Force discussed the potential to add examples. On the surface, this sounds like a good idea, but finding concrete examples of “sets of software” proves difficult.  However, we have decided not to add affirmative examples to the document for the following reasons:

* The guidance wouldn't be company/technology agnostic if we try to capture specific examples.
* Technology changes over the years, so examples are only relevant for the specific moment in time when we are writing the guidance. Specific examples would become stale over time.

The Task Force is declining to add more examples to the following, for these reasons:
* 1.3.5 Input Purpose: iOS or Android is a likely example where it will be relevant, but this Task Force is not in a position to decide whether there is currently sufficient accessibility support.
* 1.4.12 Text Spacing: Examples are sufficiently addressed in Note 1: "Examples of markup languages that are used internally...."
* 1.4.10 Reflow: This criterion links to the definition of "CSS pixel," which includes examples of platforms that use a density-independent pixel.

Like some of your other good suggestions, this could be something developed outside of the work of this task force. As a W3C Note, development of WCAG2ICT is constrained by a comprehensive and time consuming process to update. Examples such as this might be better documented in a Wiki or other easily updated resource.

**Comment by mraccess77** [comment]
It is my understanding that input type is not the same as input purpose and because of that I am glad we are not including including iOS or Android examples as I don't know if the current support for type would actually be required for the criterion 1.3.5.

**Comment by maryjom** [comment]
Closing this issue as answered.

**Comment by jamieherrera** [comment]
So... is this thread just not going to acknowledge the existence of the sibling MATF group for questions of iOS/ Android implementation?

**Comment by maryjom** [comment]
> So... is this thread just not going to acknowledge the existence of the sibling MATF group for questions of iOS/ Android implementation?

@jamieherrera Any thread comments regarding "sets of software" in this issue is off-topic, and is no longer being discussed here. This issue is regarding affirmative examples for the SCs 1.3.5 Input Purpose, 1.4.12 Text Spacing, and 1.4.10 Reflow and has been closed for 5 months. 

The TF did not ignore the existence of MATF or its document and had, in fact, added a linked reference to that draft document, noting that the MATF document is actively being updated. See the unordered list in the [Guidance in this Document](https://w3c.github.io/wcag2ict/#guidance-in-this-document) section of the current editor's draft.

However, in the pre-publication review the AG WG expressed concern with our WCAG2ICT Note referencing a draft document - see Issue #383. The suggested change is to remove the direct link to the MATF draft document and instead point to a more generic and evergreen link to a more expansive list of AG WG documents. Such a change would also mean that direct mention of MATF work would be removed. Rather than add comments to a closed issue, you might want to view and weigh in on issue 383 or open a new issue and indicate what changes you suggest.
