### ISSUE TITLE
Adjust links in Guidance Section to link to all taskforce and AG publications

### ISSUE THREAD

**Issue by rachaelbradley** [w3c/wcag2ict#383]
In the guidance section, after the newly revised paragraph to address [#77,](https://github.com/w3c/wcag2ict/issues/77), please consider the following changes to allow for more flexibility over time:

Although they have not been changed to fully apply in non-web contexts, the WCAG AAA Success Criteria and the following supporting documents  contain helpful information to learn about the user needs, intent, and generalized implementation techniques to support a wider range of people with disabilities:
- [Additional Accessibility Guidelines Working Group - Publications](https://www.w3.org/groups/wg/ag/publications/) 
- [WCAG 2 Overview](https://www.w3.org/WAI/intro/wcag.php)
- [Techniques for WCAG 2.2](https://www.w3.org/WAI/WCAG22/Techniques/) [[WCAG22-TECHS](https://w3c.github.io/wcag2ict/#bib-wcag22-techs)]
- [How to Meet WCAG (Quick Reference)](https://www.w3.org/WAI/WCAG22/quickref/)

**Comment by maryjom** [comment]
To be honest, I’m a little worried about referring to this page - especially considering the broad nature of the list it contains. Readers of WCAG2ICT would have to wade through a total of 25 documents to find the 4 to 5 documents that are relevant. These are found in the Working Drafts or FPWD sub-lists toward the end. Adding to the cognitive load, the documents on this page are listed by document type rather than by each standard with its associated supporting documents. IMO, the time and cognitive energy it would take to find the pertinent documents might deter people from looking.
 
As you mentioned in today’s WCAG2ICT meeting, it would be nice to have a list regarding specific user needs and/or research on addressing those needs, as well as specifics on certain technologies (like mobile) which are the parts most relevant to WCAG2ICT. This would be the most useful list, and could perhaps be in a Google doc for easy access with AG WG chairs and TF chairs as editors.
 
Some things I observed on this list of publications page:
* Four obviously outdated items - the Notes for WCAG 1.0 - which is odd because WCAG 1.0 is retired (per the last item on the page). All are dated from the year 2000. Is there a process for marking old Notes as retired?
* The document “Accessibility Requirements for People with Low Vision” – the title reads like this is a standard, yet it is non-normative. It is geared towards documenting user needs of people with low vision. It appears to be a very useful resource, though I’m not sure how current it is, as it's 8 years old.

Several documents that are listed are not pertinent as described in the context of this section of WCAG2ICT content that we introduced as "supporting documents contain helpful information to learn about the user needs, intent, and generalized implementation techniques to support a wider range of people with disabilities":
    * Three of the top four items in that page are WCAG versions – which aren’t really supporting documents, they are the subject of WCAG2ICT and already referenced earlier in the document.
    * The two ACT Rules documents
    * Requirements for the standards (e.g. Requirements for WCAG 2.0, 3.0, extensions) – intended for the AG WG or standards development
    * Several WCAG 3.0 documents - intended for the new standard under development, which are not supporting documents for WCAG2 and are not in scope for this version of WCAG2ICT.

**Comment by maryjom** [comment]
I will leave this issue open, as the AG leaders are developing a web page with cleaner supporting document references that we can replace the [Mobile Accessibility: How WCAG 2.0 and other W3C /WAI Guidelines Apply to Mobile](https://w3c.github.io/Mobile-A11y-TF-Note/) with a more generic link.  For now, I've added the following statement to the bullet that refers to this mobile resource so the bullet reads: 

>- [Mobile Accessibility: How WCAG 2.0 and other W3C /WAI Guidelines Apply to Mobile](https://w3c.github.io/Mobile-A11y-TF-Note/) - This draft resource, as of the date of the WCAG2ICT Note publication, is undergoing an update by the Mobile Accessibility Task Force to cover WCAG 2.2.

**Comment by bruce-usab** [comment]
The four resources Rachael lists are particularly useful and on point for WCAG2ICT.  They are also evergreen URLs.  I am in favor of including them.  I am of the opinion that we should _not_ include github.io URLs.  (The Additional Publication page fills in any gaps.)

**Comment by bruce-usab** [comment]
Discuss 8/1, looking to volunteer to draft.

**Comment by pday1** [comment]
Refer to the other TF pages, and state that there may be helpful guidance developed by specific task forces; refer to the publications from these various groups. https://www.w3.org/WAI/about/groups/task-forces/

**Comment by maryjom** [comment]
@rachaelbradley thank you for your review of WCAG2ICT and your comment. The WCAG2ICT task force agreed to remove the link to the MATF draft document. We have included your alternative link and some of the suggested changes to the sentence prior to that list (with a few edits). You can read the changes in-context in the [Guidance in this Document](https://w3c.github.io/wcag2ict/#guidance-in-this-document) section of the editor’s draft.

**Comment by maryjom** [comment]
Closed as completed.
