### ISSUE TITLE
Privacy considerations

### ISSUE THREAD

**Issue by sandandsnow** [w3c/wcag2ict#446]
PING discussed the privacy review today. In the privacy considerations, where you state "This Working Group Note does not introduce any new privacy considerations", we would like to suggest adding the following text: "However, when implementing the WCAG 2.2 guidelines and success criteria in the context of non Web information and communication technologies, information about users' accessibility needs or preferences may be exposed and should be protected from disclosure and misuse in the non Web context. Further, when implementing the guidelines and success criteria, choose implementations that reduce the potential for fingerprinting or other identification and tracking of users, and only collect the data necessary to enable the accessibility features."

**Comment by maryjom** [comment]
@sandandsnow Thank you for your comment. The Task Force will be working on resolution by initially working in the Horizontal Review Google doc where this issue proposal and potentially some edits developed and reviewed. See the [Google doc section for Issue 446](https://docs.google.com/document/d/1YfD_Rxeg72vLZXBuV05BDvlKFCjwy5KZEOeeJSTtfLY/edit#heading=h.5flqkh1efw36) where your suggested edits appear as "Proposal 1." 

Note that this Task Force's scope of work does not allow us to suggest implementation techniques or add any requirements. Since privacy considerations aren't directly covered in WCAG criteria, and WCAG2ICT is a non-normative document, we have to be mindful of the way such considerations are worded and may edit your text suggestion before incorporating it into the document. As an example, WCAG2ICT refrains from using normative language "should", "shall", "may", "must", etc. Proposal 2 in the Google doc provides an example of potential edits and we would welcome your feedback on those edits. 

You should have access when using the Google doc link and are welcome to make comment on the proposed edits in that document.

**Comment by sandandsnow** [comment]
thank you @maryjom, I have reviewed proposal 2 in the Google doc. That language is fine too.

**Comment by ChrisLoiselle** [comment]
@maryjom https://github.com/w3c/wcag2ict/pull/452 covers this discussion thread. Let me know if you need anything else pertaining to this thread.

**Comment by maryjom** [comment]
@sandandsnow Thank you for your review of the privacy considerations. The WCAG2ICT TF has updated the Privacy considerations in the editor’s draft with the following text:

>This Working Group Note does not introduce any new privacy considerations. However, when implementing WCAG 2 success criteria in the context of non-web ICT, information about a user’s accessibility needs or preferences might be exposed; a user could be harmed by disclosure and misuse of that information. It is best practice to choose implementations that reduce the potential for fingerprinting or other identification and tracking of users, and that the only data collected is data necessary to enable the accessibility features.

The task force also added a reference to the WCAG 2 privacy considerations section as we thought it provided additional information that is also pertinent to non-web documents and software. The following text was added for that reference:

>NOTE: The [WCAG 2 Privacy Considerations section](https://www.w3.org/TR/WCAG22/#privacy-summary) also notes specific success criteria that are identified to have possible implications for privacy that could also exist for non-web ICT.

You can read the changes in-context in the updated editor’s draft [Privacy Considerations](https://w3c.github.io/wcag2ict/#privacy-considerations) section.

**Comment by maryjom** [comment]
Closing as this change has been completed. @sandandsnow if there are further concerns, either reopen this issue or create a new one. Thanks again for your review.
