### ISSUE TITLE
Programmatically determine the language of text

### ISSUE THREAD

**Issue by xfq** [w3c/wcag2ict#463]
https://www.w3.org/TR/wcag2ict-22/#applying-sc-3-1-2-language-of-parts-to-non-web-documents-and-software

> The human language of each passage or phrase in the [non-web document or software] can be programmatically determined except for proper names, technical terms, words of indeterminate language, and words or phrases that have become part of the vernacular of the immediately surrounding text.

What are you trying to accomplish in this statement? Does "[programmatically determined](https://www.w3.org/TR/wcag2ict-22/#dfn-programmatically-determinable)" mean heuristic detection of language? If so, please note that such detection will often be wrong.

Also, why do these exceptions exist?

**Comment by mitchellevan** [comment]
I agree 100% with @GreggVan's last comment.

In addition, there is another scenario. With or without AI, a web app or native app might use automation, built into the app itself, to mark up its own content programmatically (i.e., with the HTML `lang` attribute or a native code equivalent). Such an automated mechanism could pass SC 3.1.2 Language of Parts — but only if the mechanism made no mistakes or omissions, which is unlikely today.

**Comment by r12a** [comment]
Does 'programmatically determined' mean:
1. can be guessed at from plain text using heuristics, by a program which then adds markers or field boundaries such as lang attributes
2. can be identified by a program from existing markup or other annotations in the text, etc.

The wording of the [definition of that phrase](https://www.w3.org/TR/wcag2ict-22/#dfn-programmatically-determinable) is so vague that i can't really tell which of these two opposing meanings is relevant.

**Comment by xfq** [comment]
We discussed this during the 8 August i18n working group teleconference, and we would like AG to add a note to clarify the intention of this statement, especially about the list of exceptions:

> except for proper names, technical terms, words of indeterminate language, and words or phrases that have become part of the vernacular of the immediately surrounding text

**Comment by ChrisLoiselle** [comment]
@mitchellevan @GreggVan @xfq , do you have a proposal that we could bring forward ? Happy to assist. @pday1 for reference, either you or I can add to Google Doc and move forward.

**Comment by ChrisLoiselle** [comment]
@maryjom see prior comment. I've self-assigned.

**Comment by GreggVan** [comment]
@r12a asked
> Does 'programmatically determined' mean
> - can be guessed at from plain text using heuristics, by a program which then adds markers or field boundaries such as lang attributes\
> - can be identified by a program from existing markup or other annotations in the text, etc.

Well - almost both.     But heuristics is **NOT** the right word   ([see definition in Wiktionary](https://en.wiktionary.org/w/index.php?title=heuristic&rdfrom=Heuristic))

- Determined does not mean "guessed".\   
( and a definition should not include what is done after the determination). 

@ChrisLoiselle  asked for wording for definition so here you are.
> **programmatically determined'** (as used in WCAG)
>
>    determined by software using the content as input

- >  NOTE 1:  Today many things need to have extra metadata or markup in order to be determined by software.  Other things can be determined by software today without the need for any markup.   As we go forward software will be increasingly able to determine anything about content that a human can determine with sight.

- > NOTE 2: With regard to accessibility, we generally don't consider something as programmatically determined (or programmatically determinable ) until it can be and is determined by the majority of affordable (free or low cost) browsers and AT (user agents).   Thus markup is required today in places it may not be in the future.

**Comment by ChrisLoiselle** [comment]
@xfq is your ask to AG or WCAG2ICT ? If WCAG2ICT, @xfq please provide a proposal of the change that I can then bring to the task force for response. Thanks for clarifying!

**Comment by xfq** [comment]
Sorry, I was asking WCAG2ICT. I cannot give a proposal at the moment, because we want to first get clarification about the intention behind this statement, especially the intention of the list of exceptions:

> except for proper names, technical terms, words of indeterminate language, and words or phrases that have become part of the vernacular of the immediately surrounding text

because we think the statement (and the definition of "programmatically determined") is rather vague, and readers who read this sentence may not necessarily understand how the language is determined, nor why these exceptions exist.

**Comment by bruce-usab** [comment]
@xfq -- please share if you are satisfied (or not) with the explanations provided.

> Does "[programmatically determined](https://www.w3.org/TR/wcag2ict-22/#dfn-programmatically-determinable)" mean _heuristic_ detection...

The definition means _algorithmic_ detection.

**Comment by maryjom** [comment]
Final WCAG2ICT Task Force Answer:

@xfq Thank you for your comment. To answer your questions:

>Does "[programmatically determined](https://www.w3.org/TR/wcag2ict-22/#dfn-programmatically-determinable)" mean heuristic detection of language?
Programmatically determined means determined by software from author-supplied data, per the definition of ‘[programmatically determined](https://www.w3.org/TR/WCAG22/#dfn-programmatically-determinable)’ in WCAG. Examples are provided indicating what would be considered author-supplied data that user agents and assistive technologies can extract and present to the user (e.g. markup language elements and attributes or technology-specific data structures today and possibly direct determination by software in the future).

>Why do these exceptions exist?

These exceptions were defined by WCAG 2.0 (and have persisted without change ever since). 

Note that the WCAG2ICT TF has not modified these exceptions in any way. The only changes WCAG2ICT made to the language for 3.1.2 Language of Parts is the word substitution exchanging web-centric terms with terms more applicable to non-web technologies. Per the WCAG2ICT Task Force’s scope of work, we are unable to change the meaning of a requirement by modifying normative language, including the exceptions.

If there is a concern with the exceptions or with the definition of “programmatically determined,” we recommend that you [raise an issue in the WCAG repository](https://github.com/w3c/wcag/issues/new). The WCAG2ICT repository is limited to comments on the interpretation, word substitutions, and notes describing how to apply WCAG in an non-web context.  You could also refer to WCAG 2.2 [Understanding SC 3.1.2 Language of Parts](https://www.w3.org/WAI/WCAG22/Understanding/language-of-parts).
 
Unless the WCAG language gets changed by the Accessibility Guidelines Working Group (AGWG), the WCAG2ICT Task Force cannot make any further modifications to them in the WCAG2ICT Group Note.

**Comment by xfq** [comment]
Thank you for your reply. We discussed this during the 5 September i18n working group teleconference.

We understand that the definition of ‘programmatically determined’ and the list of exceptions are based on WCAG. The i18n WG has been promoting language metadata for strings (see [specdev](https://www.w3.org/TR/international-specs/#language) and [string-meta](https://www.w3.org/TR/string-meta/)). One of the reasons is that without language metadata, the language can only be determined accurate enough for a small number of languages ​​through some algorithm (AI for language detection is improving, but it can still give false positives). We would like WCAG2ICT to have a note to point this out and encourage authors to provide language metadata (by using markup, for example) when possible.

For the text in WCAG, we hope to change this sentence to something like this (we will raise an issue against WCAG):

> You SHOULD programmatically determine the language of the text. If metadata or author-supplied information about the language is not available, you MAY use a heuristic (or algorithm) to determine the language.

**Comment by maryjom** [comment]
@xfq It is good to see that the i18n is promoting language metadata, as this helps content developers have documented methods of meeting SC 3.1.2 Language of Parts. Once published, these Notes will be good documents for WCAG  to reference. 

Because all of the content in the WCAG2ICT Note is non-normative, our Task Force has to be mindful to not provide techniques for meeting or not meeting particular success criteria. Doing so would be going outside of our statement of work.

However, we could encourage use of actual metadata and markup by providing that as an example in our note on 3.1.2 Language of Parts, drafted below.  

Here's a possible draft change to the note in WCAG2ICT (by adding the first sentence):
> Note 1: Examples of programmatic identification include language metadata or markup. There are some [software](https://w3c.github.io/wcag2ict/#software) and [non-web document](https://w3c.github.io/wcag2ict/#document) technologies where there is no assistive technology supported method for marking the language for the different passages or phrases in the non-web document or software, and it would not be possible to meet this success criterion with those technologies.

Would this change be sufficient to address your concern? If not, please help us draft what you are looking for, as we are very close to publication of the finalized WCAG2ICT Group Note and need to get any substantive changes incorporated as soon as possible for the AG WG final review before their CfC to publish.

**Comment by xfq** [comment]
Works for me. We will continue to discuss changes with the WCAG folks. Thank you for working on this!

**Comment by maryjom** [comment]
Closing as answered. Thanks @xfq.

**Comment by xfq** [comment]
I don't seem to see these changes in https://w3c.github.io/wcag2ict/#applying-sc-3-1-2-language-of-parts-to-non-web-documents-and-software . Are the changes still pending?

**Comment by daniel-montalvo** [comment]
Hi @xfq @maryjom 

I also don't seem to find any PR addressing this. I'll reopen this issue, link a PR, so that the issue closes when the PR is merged.
